export type TranslationKeys =
  | 'siteTitle'
  | 'aboutMe'
  | 'myWorks'
  | 'experience'
  | 'education'
  | 'skills'
  | 'contact'
  | 'linkedin'
  | 'instagram'
  | 'email'
  | 'menu'
  | 'contactWays'
  | 'call'
  | 'siteExample'

  // First section
  | 'contactButton'
  | 'name'
  | 'role'
  | 'description'
  | 'resumeButton'
  | 'no'
  | 'greeting'

  // Second section
  | 'servicesTitle'
  | 'reactDeveloper'
  | 'reactDescription'
  | 'nextJsDeveloper'
  | 'nextJsDescription'
  | 'wordpressDeveloper'
  | 'wordpressDescription'
  | 'biographyTitle'
  | 'biographyText1'
  | 'biographyText2'
  | 'fullName'
  | 'birthDate'
  | 'fieldOfStudy'
  | 'location'
  | 'technologies'

  // Third section
  | 'educationTitle'
  | 'bachelorsDegree'
  | 'bojnourdUniversity'
  | 'computerScience'
  | 'studyPeriodBachelor'
  | 'mastersDegree'
  | 'hakimSabzevariUniversity'
  | 'computerScienceDecision'
  | 'studyPeriodMaster'
  | 'workExperienceTitle'
  | 'oghoghPc'
  | 'technicalManager'
  | 'software'
  | 'roshanAgency'
  | 'wordpressDesigner'
  | 'portfolioSamples'
  | 'freelanceProjects'
  | 'freelanceWorksTitle'
  | 'sinceYear'
  | 'chapDeniz'
  | 'hearingAid'
  | 'heydariSpareParts'
  | 'aresAgro'
  | 'carvich'
  | 'lavacorn'
  | 'portfolioTitle'
  | 'freelanceTitle'

  // Fourth section - Skills
  | 'skillsTitle'
  | 'wordpress'
  | 'coding'
  | 'wordpressDesign'
  | 'seo'
  | 'googleAnalytics'
  | 'elementor'
  | 'reactJs'
  | 'nextJs'
  | 'muiDesign'
  | 'api'
  | 'reactQuery';

export type Translations = {
  [key in TranslationKeys]: string;
};
